# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Accounts do
  @moduledoc """
  API calls for all endpoints tagged `Accounts`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Single account
  Returns a single account

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget)
  - account_id (String.t): The id of the account
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.AccountResponse{}} on success
  {:error, info} on failure
  """
  @spec get_account_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.AccountResponse.t()} | {:error, Tesla.Env.t()}
  def get_account_by_id(client, budget_id, account_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/accounts/#{account_id}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.AccountResponse{})
  end

  @doc """
  Account list
  Returns all accounts

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget)
  - opts (KeywordList): [optional] Optional parameters
    - :last_knowledge_of_server (integer()): The starting server knowledge.  If provided, only entities that have changed since last_knowledge_of_server will be included.

  ## Returns

  {:ok, %YNAB.Model.AccountsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_accounts(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.AccountsResponse.t()} | {:error, Tesla.Env.t()}
  def get_accounts(client, budget_id, opts \\ []) do
    optional_params = %{
      last_knowledge_of_server: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/accounts")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.AccountsResponse{})
  end
end
