# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Accounts do
  @moduledoc """
  API calls for all endpoints tagged `Accounts`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Single account
  Returns a single account

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - account_id (String.t): The ID of the Account.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.AccountResponse{}} on success
  {:error, info} on failure
  """
  @spec get_account_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.AccountResponse.t()} | {:error, Tesla.Env.t()}
  def get_account_by_id(client, budget_id, account_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/accounts/#{account_id}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.AccountResponse{})
  end

  @doc """
  Account list
  Returns all accounts

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.AccountsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_accounts(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.AccountsResponse.t()} | {:error, Tesla.Env.t()}
  def get_accounts(client, budget_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/accounts")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.AccountsResponse{})
  end
end
