# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Budgets do
  @moduledoc """
  API calls for all endpoints tagged `Budgets`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Single budget
  Returns a single budget with all related entities.  This resource is effectively a full budget export.

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - opts (KeywordList): [optional] Optional parameters
    - :last_knowledge_of_server (integer()): The starting server knowledge.  If provided, only entities that have changed since last_knowledge_of_server will be included.

  ## Returns

  {:ok, %YNAB.Model.BudgetDetailResponse{}} on success
  {:error, info} on failure
  """
  @spec get_budget_by_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.BudgetDetailResponse.t()} | {:error, Tesla.Env.t()}
  def get_budget_by_id(client, budget_id, opts \\ []) do
    optional_params = %{
      last_knowledge_of_server: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.BudgetDetailResponse{})
  end

  @doc """
  Budget Settings
  Returns settings for a budget

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.BudgetSettingsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_budget_settings_by_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.BudgetSettingsResponse.t()} | {:error, Tesla.Env.t()}
  def get_budget_settings_by_id(client, budget_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/settings")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.BudgetSettingsResponse{})
  end

  @doc """
  List budgets
  Returns budgets list with summary information

  ## Parameters

  - client (YNAB.Client): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.BudgetSummaryResponse{}} on success
  {:error, info} on failure
  """
  @spec get_budgets(Tesla.Env.client(), keyword()) ::
          {:ok, YNAB.Model.BudgetSummaryResponse.t()} | {:error, Tesla.Env.t()}
  def get_budgets(client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.BudgetSummaryResponse{})
  end
end
