# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Categories do
  @moduledoc """
  API calls for all endpoints tagged `Categories`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  List categories
  Returns all categories grouped by category group.

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.CategoriesResponse{}} on success
  {:error, info} on failure
  """
  @spec get_categories(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.CategoriesResponse.t()} | {:error, Tesla.Env.t()}
  def get_categories(client, budget_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/categories")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.CategoriesResponse{})
  end

  @doc """
  Single category
  Returns a single category

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - category_id (String.t): The ID of the Category.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.CategoryResponse{}} on success
  {:error, info} on failure
  """
  @spec get_category_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.CategoryResponse.t()} | {:error, Tesla.Env.t()}
  def get_category_by_id(client, budget_id, category_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/categories/#{category_id}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.CategoryResponse{})
  end
end
