# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Deprecated do
  @moduledoc """
  API calls for all endpoints tagged `Deprecated`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Bulk create transactions
  Creates multiple transactions.  Although this endpoint is still supported, it is recommended to use &#39;POST /budgets/{budget_id}/transactions&#39; to create multiple transactions.

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget)
  - transactions (BulkTransactions): The list of transactions to create
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.BulkResponse{}} on success
  {:error, info} on failure
  """
  @spec bulk_create_transactions(
          Tesla.Env.client(),
          String.t(),
          YNAB.Model.BulkTransactions.t(),
          keyword()
        ) :: {:ok, YNAB.Model.BulkResponse.t()} | {:error, Tesla.Env.t()}
  def bulk_create_transactions(client, budget_id, transactions, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/budgets/#{budget_id}/transactions/bulk")
    |> add_param(:body, :transactions, transactions)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.BulkResponse{})
  end
end
