# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Months do
  @moduledoc """
  API calls for all endpoints tagged `Months`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Single budget month
  Returns a single budget month

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - month (Date.t): The budget month in ISO format (e.g. 2016-12-30) (\&quot;current\&quot; can also be used to specify the current calendar month (UTC))
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.MonthDetailResponse{}} on success
  {:error, info} on failure
  """
  @spec get_budget_month(Tesla.Env.client(), String.t(), Date.t(), keyword()) ::
          {:ok, YNAB.Model.MonthDetailResponse.t()} | {:error, Tesla.Env.t()}
  def get_budget_month(client, budget_id, month, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/months/#{month}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.MonthDetailResponse{})
  end

  @doc """
  List budget months
  Returns all budget months

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.MonthSummariesResponse{}} on success
  {:error, info} on failure
  """
  @spec get_budget_months(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.MonthSummariesResponse.t()} | {:error, Tesla.Env.t()}
  def get_budget_months(client, budget_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/months")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.MonthSummariesResponse{})
  end
end
