# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.PayeeLocations do
  @moduledoc """
  API calls for all endpoints tagged `PayeeLocations`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Single payee location
  Returns a single payee location

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - payee_location_id (String.t): ID of payee location
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.PayeeLocationResponse{}} on success
  {:error, info} on failure
  """
  @spec get_payee_location_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationResponse.t()} | {:error, Tesla.Env.t()}
  def get_payee_location_by_id(client, budget_id, payee_location_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/payee_locations/#{payee_location_id}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.PayeeLocationResponse{})
  end

  @doc """
  List payee locations
  Returns all payee locations

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.PayeeLocationsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_payee_locations(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationsResponse.t()} | {:error, Tesla.Env.t()}
  def get_payee_locations(client, budget_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/payee_locations")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.PayeeLocationsResponse{})
  end

  @doc """
  List locations for a payee
  Returns all payee locations for the specified payee

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The ID of the Budget.
  - payee_id (String.t): ID of payee
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.PayeeLocationsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_payee_locations_by_payee(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationsResponse.t()} | {:error, Tesla.Env.t()}
  def get_payee_locations_by_payee(client, budget_id, payee_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/payees/#{payee_id}/payee_locations")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.PayeeLocationsResponse{})
  end
end
