# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.Transactions do
  @moduledoc """
  API calls for all endpoints tagged `Transactions`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  Create a single transaction or multiple transactions
  Creates a single transaction or multiple transactions.  If you provide a body containing a &#39;transaction&#39; object, a single transaction will be created and if you provide a body containing a &#39;transactions&#39; array, multiple transactions will be created.

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - save_transactions (SaveTransactionsWrapper): The transaction or transactions to create
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.SaveTransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec create_transaction(
          Tesla.Env.client(),
          String.t(),
          YNAB.Model.SaveTransactionsWrapper.t(),
          keyword()
        ) :: {:ok, YNAB.Model.SaveTransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def create_transaction(client, budget_id, save_transactions, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/budgets/#{budget_id}/transactions")
    |> add_param(:body, :save_transactions, save_transactions)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.SaveTransactionsResponse{})
  end

  @doc """
  Single transaction
  Returns a single transaction

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - transaction_id (String.t): The id of the transaction
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.TransactionResponse{}} on success
  {:error, info} on failure
  """
  @spec get_transaction_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.TransactionResponse.t()} | {:error, Tesla.Env.t()}
  def get_transaction_by_id(client, budget_id, transaction_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/transactions/#{transaction_id}")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.TransactionResponse{})
  end

  @doc """
  List transactions
  Returns budget transactions

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - opts (KeywordList): [optional] Optional parameters
    - :since_date (Date.t): Only return transactions on or after this date
    - :type (String.t): Only return transactions of a certain type (&#39;uncategorized&#39; and &#39;unapproved&#39; are currently supported)

  ## Returns

  {:ok, %YNAB.Model.TransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_transactions(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.TransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def get_transactions(client, budget_id, opts \\ []) do
    optional_params = %{
      since_date: :query,
      type: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/transactions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.TransactionsResponse{})
  end

  @doc """
  List account transactions
  Returns all transactions for a specified account

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - account_id (String.t): The id of the account
  - opts (KeywordList): [optional] Optional parameters
    - :since_date (Date.t): Only return transactions on or after this date
    - :type (String.t): Only return transactions of a certain type (i.e. &#39;uncategorized&#39;, &#39;unapproved&#39;)

  ## Returns

  {:ok, %YNAB.Model.TransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_transactions_by_account(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.TransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def get_transactions_by_account(client, budget_id, account_id, opts \\ []) do
    optional_params = %{
      since_date: :query,
      type: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/accounts/#{account_id}/transactions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.TransactionsResponse{})
  end

  @doc """
  List category transactions
  Returns all transactions for a specified category

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - category_id (String.t): The id of the category
  - opts (KeywordList): [optional] Optional parameters
    - :since_date (Date.t): Only return transactions on or after this date
    - :type (String.t): Only return transactions of a certain type (i.e. &#39;uncategorized&#39;, &#39;unapproved&#39;)

  ## Returns

  {:ok, %YNAB.Model.HybridTransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_transactions_by_category(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.HybridTransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def get_transactions_by_category(client, budget_id, category_id, opts \\ []) do
    optional_params = %{
      since_date: :query,
      type: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/categories/#{category_id}/transactions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.HybridTransactionsResponse{})
  end

  @doc """
  List payee transactions
  Returns all transactions for a specified payee

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - payee_id (String.t): The id of the payee
  - opts (KeywordList): [optional] Optional parameters
    - :since_date (Date.t): Only return transactions on or after this date
    - :type (String.t): Only return transactions of a certain type (i.e. &#39;uncategorized&#39;, &#39;unapproved&#39;)

  ## Returns

  {:ok, %YNAB.Model.HybridTransactionsResponse{}} on success
  {:error, info} on failure
  """
  @spec get_transactions_by_payee(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.HybridTransactionsResponse.t()} | {:error, Tesla.Env.t()}
  def get_transactions_by_payee(client, budget_id, payee_id, opts \\ []) do
    optional_params = %{
      since_date: :query,
      type: :query
    }

    %{}
    |> method(:get)
    |> url("/budgets/#{budget_id}/payees/#{payee_id}/transactions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.HybridTransactionsResponse{})
  end

  @doc """
  Updates an existing transaction
  Updates a transaction

  ## Parameters

  - client (YNAB.Client): Connection to server
  - budget_id (String.t): The id of the budget (\&quot;last-used\&quot; can also be used to specify the last used budget)
  - transaction_id (String.t): The id of the transaction
  - transaction (SaveTransactionWrapper): The transaction to update
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.TransactionResponse{}} on success
  {:error, info} on failure
  """
  @spec update_transaction(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          YNAB.Model.SaveTransactionWrapper.t(),
          keyword()
        ) :: {:ok, YNAB.Model.TransactionResponse.t()} | {:error, Tesla.Env.t()}
  def update_transaction(client, budget_id, transaction_id, transaction, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/budgets/#{budget_id}/transactions/#{transaction_id}")
    |> add_param(:body, :transaction, transaction)
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.TransactionResponse{})
  end
end
