# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Api.User do
  @moduledoc """
  API calls for all endpoints tagged `User`.
  """
  alias YNAB.Client
  import YNAB.RequestBuilder

  @doc """
  User info
  Returns authenticated user information

  ## Parameters

  - client (YNAB.Client): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %YNAB.Model.UserResponse{}} on success
  {:error, info} on failure
  """
  @spec get_user(Tesla.Env.client(), keyword()) ::
          {:ok, YNAB.Model.UserResponse.t()} | {:error, Tesla.Env.t()}
  def get_user(client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/user")
    |> Enum.into([])
    |> (&Client.request(client, &1)).()
    |> decode(%YNAB.Model.UserResponse{})
  end
end
