# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.AccountsWrapper do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts
  ]

  @type t :: %__MODULE__{
          accounts: [Account]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.AccountsWrapper do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, YNAB.Model.Account, options)
  end
end
