# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.AccountResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account
  ]

  @type t :: %__MODULE__{
          account: Account
        }
end

defimpl Poison.Decoder, for: YNAB.Model.AccountResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:account, :struct, YNAB.Model.Account, options)
  end
end
