# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.Account do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :type,
    :on_budget,
    :closed,
    :note,
    :balance,
    :cleared_balance,
    :uncleared_balance,
    :transfer_payee_id,
    :deleted
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          name: String.t(),
          type: String.t(),
          on_budget: boolean(),
          closed: boolean(),
          note: String.t(),
          balance: integer(),
          cleared_balance: integer(),
          uncleared_balance: integer(),
          transfer_payee_id: String.t(),
          deleted: boolean()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.Account do
  def decode(value, _options) do
    value
  end
end
