# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BudgetSettings do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :date_format,
    :currency_format
  ]

  @type t :: %__MODULE__{
          date_format: DateFormat,
          currency_format: CurrencyFormat
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BudgetSettings do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date_format, :struct, YNAB.Model.DateFormat, options)
    |> deserialize(:currency_format, :struct, YNAB.Model.CurrencyFormat, options)
  end
end
