# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BudgetDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :last_modified_on,
    :first_month,
    :last_month,
    :date_format,
    :currency_format,
    :accounts,
    :payees,
    :payee_locations,
    :category_groups,
    :categories,
    :months,
    :transactions,
    :subtransactions,
    :scheduled_transactions,
    :scheduled_subtransactions
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          name: String.t(),
          last_modified_on: DateTime.t(),
          first_month: Date.t(),
          last_month: Date.t(),
          date_format: DateFormat,
          currency_format: CurrencyFormat,
          accounts: [Account],
          payees: [Payee],
          payee_locations: [PayeeLocation],
          category_groups: [CategoryGroup],
          categories: [Category],
          months: [MonthDetail],
          transactions: [TransactionSummary],
          subtransactions: [SubTransaction],
          scheduled_transactions: [ScheduledTransactionSummary],
          scheduled_subtransactions: [ScheduledSubTransaction]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BudgetDetail do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:first_month, :date, nil, options)
    |> deserialize(:last_month, :date, nil, options)
    |> deserialize(:date_format, :struct, YNAB.Model.DateFormat, options)
    |> deserialize(:currency_format, :struct, YNAB.Model.CurrencyFormat, options)
    |> deserialize(:accounts, :list, YNAB.Model.Account, options)
    |> deserialize(:payees, :list, YNAB.Model.Payee, options)
    |> deserialize(:payee_locations, :list, YNAB.Model.PayeeLocation, options)
    |> deserialize(:category_groups, :list, YNAB.Model.CategoryGroup, options)
    |> deserialize(:categories, :list, YNAB.Model.Category, options)
    |> deserialize(:months, :list, YNAB.Model.MonthDetail, options)
    |> deserialize(:transactions, :list, YNAB.Model.TransactionSummary, options)
    |> deserialize(:subtransactions, :list, YNAB.Model.SubTransaction, options)
    |> deserialize(
      :scheduled_transactions,
      :list,
      YNAB.Model.ScheduledTransactionSummary,
      options
    )
    |> deserialize(:scheduled_subtransactions, :list, YNAB.Model.ScheduledSubTransaction, options)
  end
end
