# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BudgetSummaryResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :budgets,
    :default_budget
  ]

  @type t :: %__MODULE__{
          budgets: [BudgetSummary],
          default_budget: BudgetSummary
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BudgetSummaryResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:budgets, :list, YNAB.Model.BudgetSummary, options)
    |> deserialize(:default_budget, :struct, YNAB.Model.BudgetSummary, options)
  end
end
