# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BudgetSummaryWrapper do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :budgets
  ]

  @type t :: %__MODULE__{
          budgets: [BudgetSummary]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BudgetSummaryWrapper do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:budgets, :list, YNAB.Model.BudgetSummary, options)
  end
end
