# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BulkResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :bulk
  ]

  @type t :: %__MODULE__{
          bulk: BulkResponseDataBulk
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BulkResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bulk, :struct, YNAB.Model.BulkResponseDataBulk, options)
  end
end
