# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.BulkResponseDataBulk do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :transaction_ids,
    :duplicate_import_ids
  ]

  @type t :: %__MODULE__{
          transaction_ids: [String.t()],
          duplicate_import_ids: [String.t()]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.BulkResponseDataBulk do
  def decode(value, _options) do
    value
  end
end
