# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.Category do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :category_group_id,
    :name,
    :hidden,
    :budgeted,
    :activity,
    :balance
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          category_group_id: String.t(),
          name: String.t(),
          hidden: boolean(),
          budgeted: float(),
          activity: float(),
          balance: float()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.Category do
  def decode(value, _options) do
    value
  end
end
