# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.CurrencyFormat do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :iso_code,
    :example_format,
    :decimal_digits,
    :decimal_separator,
    :symbol_first,
    :group_separator,
    :currency_symbol,
    :display_symbol
  ]

  @type t :: %__MODULE__{
          iso_code: String.t(),
          example_format: String.t(),
          decimal_digits: integer(),
          decimal_separator: String.t(),
          symbol_first: boolean(),
          group_separator: String.t(),
          currency_symbol: String.t(),
          display_symbol: boolean()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.CurrencyFormat do
  def decode(value, _options) do
    value
  end
end
