# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.DateFormat do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :format
  ]

  @type t :: %__MODULE__{
          format: String.t()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.DateFormat do
  def decode(value, _options) do
    value
  end
end
