# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.ErrorDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :detail
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          name: String.t(),
          detail: String.t()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.ErrorDetail do
  def decode(value, _options) do
    value
  end
end
