# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.ErrorResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
          error: ErrorDetail
        }
end

defimpl Poison.Decoder, for: YNAB.Model.ErrorResponse do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:error, :struct, YNAB.Model.ErrorDetail, options)
  end
end
