# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.MonthSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :month,
    :note,
    :income,
    :budgeted,
    :activity,
    :to_be_budgeted,
    :age_of_money
  ]

  @type t :: %__MODULE__{
          month: Date.t(),
          note: String.t(),
          income: integer(),
          budgeted: integer(),
          activity: integer(),
          to_be_budgeted: integer(),
          age_of_money: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.MonthSummary do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:month, :date, nil, options)
  end
end
