# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.MonthDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :month,
    :categories
  ]

  @type t :: %__MODULE__{
          month: Date.t(),
          categories: [Category]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.MonthDetail do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:month, :date, nil, options)
    |> deserialize(:categories, :list, YNAB.Model.Category, options)
  end
end
