# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.MonthSummariesResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :months,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          months: [MonthSummary],
          server_knowledge: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.MonthSummariesResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:months, :list, YNAB.Model.MonthSummary, options)
  end
end
