# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.MonthSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :month
  ]

  @type t :: %__MODULE__{
          month: Date.t()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.MonthSummary do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:month, :date, nil, options)
  end
end
