# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.PayeeLocation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :payee_id
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          payee_id: String.t()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.PayeeLocation do
  def decode(value, _options) do
    value
  end
end
