# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.PayeesResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :payees,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          payees: [Payee],
          server_knowledge: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.PayeesResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:payees, :list, YNAB.Model.Payee, options)
  end
end
