# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.PayeeLocationsResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :payee_locations
  ]

  @type t :: %__MODULE__{
          payee_locations: [PayeeLocation]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.PayeeLocationsResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:payee_locations, :list, YNAB.Model.PayeeLocation, options)
  end
end
