# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.SaveTransactionsWrapper do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :transaction,
    :transactions
  ]

  @type t :: %__MODULE__{
          transaction: SaveTransaction,
          transactions: [SaveTransaction]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.SaveTransactionsWrapper do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:transaction, :struct, YNAB.Model.SaveTransaction, options)
    |> deserialize(:transactions, :list, YNAB.Model.SaveTransaction, options)
  end
end
