# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.SaveMonthCategory do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :budgeted
  ]

  @type t :: %__MODULE__{
          budgeted: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.SaveMonthCategory do
  def decode(value, _options) do
    value
  end
end
