# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.SaveMonthCategoryWrapper do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :month_category
  ]

  @type t :: %__MODULE__{
          month_category: SaveMonthCategory
        }
end

defimpl Poison.Decoder, for: YNAB.Model.SaveMonthCategoryWrapper do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:month_category, :struct, YNAB.Model.SaveMonthCategory, options)
  end
end
