# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.SaveTransaction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :date,
    :amount,
    :cleared,
    :approved
  ]

  @type t :: %__MODULE__{
          account_id: String.t(),
          date: Date.t(),
          amount: float(),
          cleared: String.t(),
          approved: boolean()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.SaveTransaction do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end
