# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.SaveTransactionsResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :transaction_ids,
    :transaction,
    :transactions,
    :duplicate_import_ids,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          transaction_ids: [String.t()],
          transaction: TransactionDetail,
          transactions: [TransactionDetail],
          duplicate_import_ids: [String.t()],
          server_knowledge: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.SaveTransactionsResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:transaction, :struct, YNAB.Model.TransactionDetail, options)
    |> deserialize(:transactions, :list, YNAB.Model.TransactionDetail, options)
  end
end
