# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.ScheduledTransactionSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :date_first,
    :date_next,
    :frequency,
    :amount,
    :memo,
    :flag_color,
    :account_id,
    :payee_id,
    :category_id,
    :transfer_account_id,
    :deleted
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          date_first: Date.t(),
          date_next: Date.t(),
          frequency: String.t(),
          amount: integer(),
          memo: String.t(),
          flag_color: String.t(),
          account_id: String.t(),
          payee_id: String.t(),
          category_id: String.t(),
          transfer_account_id: String.t(),
          deleted: boolean()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.ScheduledTransactionSummary do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date_first, :date, nil, options)
    |> deserialize(:date_next, :date, nil, options)
  end
end
