# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.ScheduledSubTransaction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :scheduled_transaction_id,
    :amount
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          scheduled_transaction_id: String.t(),
          amount: float()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.ScheduledSubTransaction do
  def decode(value, _options) do
    value
  end
end
