# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.ScheduledTransactionDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :date_first,
    :date_next,
    :frequency,
    :amount,
    :account_id,
    :account_name,
    :subtransactions
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          date_first: Date.t(),
          date_next: Date.t(),
          frequency: String.t(),
          amount: float(),
          account_id: String.t(),
          account_name: String.t(),
          subtransactions: [ScheduledSubTransaction]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.ScheduledTransactionDetail do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date_first, :date, nil, options)
    |> deserialize(:date_next, :date, nil, options)
    |> deserialize(:subtransactions, :list, YNAB.Model.ScheduledSubTransaction, options)
  end
end
