# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.TransactionsResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :transactions,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          transactions: [TransactionDetail],
          server_knowledge: integer()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.TransactionsResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:transactions, :list, YNAB.Model.TransactionDetail, options)
  end
end
