# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.TransactionDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :date,
    :amount,
    :cleared,
    :approved,
    :account_id,
    :account_name,
    :subtransactions
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          date: Date.t(),
          amount: float(),
          cleared: String.t(),
          approved: boolean(),
          account_id: String.t(),
          account_name: String.t(),
          subtransactions: [SubTransaction]
        }
end

defimpl Poison.Decoder, for: YNAB.Model.TransactionDetail do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:subtransactions, :list, YNAB.Model.SubTransaction, options)
  end
end
