# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.UpdateTransaction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :date,
    :amount,
    :payee_id,
    :payee_name,
    :category_id,
    :memo,
    :cleared,
    :approved,
    :flag_color,
    :import_id,
    :id
  ]

  @type t :: %__MODULE__{
          account_id: String.t(),
          date: Date.t(),
          amount: integer(),
          payee_id: String.t(),
          payee_name: String.t(),
          category_id: String.t(),
          memo: String.t(),
          cleared: String.t(),
          approved: boolean(),
          flag_color: String.t(),
          import_id: String.t(),
          id: String.t()
        }
end

defimpl Poison.Decoder, for: YNAB.Model.UpdateTransaction do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end
