# NOTE: This file is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit manually.

defmodule YNAB.Model.UserResponseData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :user
  ]

  @type t :: %__MODULE__{
          user: User
        }
end

defimpl Poison.Decoder, for: YNAB.Model.UserResponseData do
  import YNAB.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user, :struct, YNAB.Model.User, options)
  end
end
